// apps/frontend/src/components/ui/BaseAlwaysScrollable.vue
<template>
  <div class="overflow-hidden relative inline-flex" ref="container">
    <div
      :style="{
        '--scroll-x-diff': diffFormatted,
        '--scroll-x-duration': duration,
      }"
      class="whitespace-nowrap m-(--base-always-scrollable--content--margin)"
      :class="isAnimated && 'animate-scroll-x [animation-duration:var(--scroll-x-duration)]'"
      ref="content"
    >
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useElementSize } from '@vueuse/core';
import { computed, useTemplateRef } from 'vue';

withDefaults(
  defineProps<
    Partial<{
      duration: string;
    }>
  >(),
  {
    duration: '5000ms',
  },
);

const container = useTemplateRef('container');
const content = useTemplateRef('content');

const { width: widthContainer } = useElementSize(container, undefined, { box: 'border-box' });
const { width: widthContent } = useElementSize(content, undefined, { box: 'border-box' });

const diff = computed(() => {
  return widthContent.value - widthContainer.value;
});

const diffFormatted = computed(() => {
  return `-${diff.value}px`;
});

const isAnimated = computed(() => {
  return diff.value > 0;
});
</script>

// apps/frontend/components/base-always-scrollable.tsx
'use client';

import { type CSSProperties, type PropsWithChildren, useEffect, useRef, useState } from 'react';
import { cn } from '@/lib/utils/cn';

type BaseAlwaysScrollableProps = PropsWithChildren<{
  className?: string;
  duration?: string;
}>;

export const BaseAlwaysScrollable = ({ children, className, duration = '5000ms' }: BaseAlwaysScrollableProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const [scrollDifference, setScrollDifference] = useState(0);

  useEffect(() => {
    const container = containerRef.current;
    const content = contentRef.current;

    if (!(container && content)) {
      return;
    }

    const updateScrollDifference = () => {
      setScrollDifference(content.offsetWidth - container.offsetWidth);
    };
    const observer = new ResizeObserver(updateScrollDifference);

    observer.observe(container);
    observer.observe(content);
    updateScrollDifference();

    return () => {
      observer.disconnect();
    };
  }, []);

  const style = {
    '--scroll-x-diff': `-${scrollDifference}px`,
    '--scroll-x-duration': duration,
  } as CSSProperties;

  return (
    <div className="relative inline-flex overflow-hidden" ref={containerRef}>
      <div
        className={cn(
          'm-(--base-always-scrollable--content--margin) whitespace-nowrap',
          scrollDifference > 0 && 'animate-scroll-x',
          className,
        )}
        ref={contentRef}
        style={style}
      >
        {children}
      </div>
    </div>
  );
};
