// apps/frontend/src/components/ui/BaseVideo.vue
<template>
  <div class="flex justify-center items-center max-w-full relative">
    <BaseIcon class="absolute text-items size-1/3" :path="mdiPlayCircleOutline" />
    <video class="max-w-full" :src />
  </div>
</template>

<script setup lang="ts">
import { mdiPlayCircleOutline } from '@mdi/js';
import BaseIcon from '@/components/ui/BaseIcon.vue';

defineProps<{
  src: string;
}>();
</script>

// apps/frontend/components/base-video.tsx
import { cn } from '@/lib/utils/cn';
import { PlayCircle } from 'lucide-react';

export const BaseVideo = ({ className, ...props }: React.ComponentProps<'video'>) => {
  return (
    <div className={cn('flex justify-center items-center max-w-full relative', className)}>
      <video className="max-w-full" {...props} />
      <PlayCircle className="absolute text-primary size-1/5 pointer-events-none" />
    </div>
  );
};
