// apps/frontend/src/views/Explorer/components/ExplorerElementFileImage.vue
<template>
  <ElementFileWrapper :to :element>
    <img
      class="explorer-element__body max-w-full mx-auto"
      :width="element.metadata.width"
      :height="element.metadata.height"
      :src="element.src"
      :alt="element.name"
    />
  </ElementFileWrapper>
</template>

<script setup lang="ts">
import ElementFileWrapper from './_ElementFileWrapper.vue';
import type { Props as PropsElementFileWrapper } from './_ElementFileWrapper.vue';
import type { components } from '@/types/openapi';

defineProps<{
  element: components['schemas']['FolderDataItemImage'];
  to: PropsElementFileWrapper['to'];
}>();
</script>

// apps/frontend/app/[locale]/explorer/[[...segments]]/_components/explorer-element-file/explorer-element-file-image.tsx
import { Item, ItemHeader, ItemMedia } from '@/components/ui/item';
import Image from 'next/image';
import { Link } from '@/i18n/navigation';
import { components } from '@/lib/types/openapi';
import { ComponentProps } from 'react';
import { Separator } from '@/components/ui/separator';
import { ExplorerElementTime } from './explorer-element-time';

export const ExplorerElementFileImage = ({
  element,
  ...props
}: ComponentProps<typeof Link> & { element: components['schemas']['FolderDataItemImage'] }) => {
  return (
    <article className="contents">
      <Item className="border-primary" variant="outline" render={<Link {...props} />}>
        <ItemHeader>
          <header className="text-lg">{element.name}</header>
          <ExplorerElementTime element={element} />
        </ItemHeader>
        <Separator />
        <ItemMedia className="mx-auto max-w-full">
          <Image src={element.src} alt={element.name} width={element.metadata.width} height={element.metadata.height} />
        </ItemMedia>
      </Item>
    </article>
  );
};
