// apps/frontend/src/components/ThePlayer/ThePlayer.vue
<template>
  <BaseSwipable data-player class="bg-background z-player border-t border-primary-500 py-2 w-full" @swiped="onSwiped">
    <div class="layout-container flex flex-col gap-1 justify-center">
      <component
        :is="ComponentClose"
        v-if="shouldRenderButtonClose"
        class="text-xl absolute end-2 top-2 hover-none:hidden"
        :class="BUTTON._SECONDARY"
        :aria-label="t('closePlayer')"
        @click="onClickClose"
      >
        <BaseIcon :path="mdiClose" />
      </component>
      <BaseAlwaysScrollable class="[--base-always-scrollable--content--margin:0_auto]">
        <header class="cursor-pointer flex items-center gap-0.5" :title="t('copyLink')" @click="onClickTitle">
          <h2>{{ player.theTrack.value?.name }}</h2>
          <BaseIcon :path="mdiLinkVariant" />
        </header>
      </BaseAlwaysScrollable>
      <audio :src="player.theTrack.value?.src" autoplay ref="audio" @ended="onEnded" />
      <div class="h-5 w-full mx-auto flex justify-between items-center gap-2">
        <time :datetime="currentTimeFormats.iso">
          {{ currentTimeFormats.humanReadable }}
        </time>
        <PlayerSlider
          :multiplier="duration / 1000"
          isLazy
          v-model="currentTimeSeconds"
          @keydown.right="onKeyDownRightTime"
          @keydown.left="onKeyDownLeftTime"
        />
        <time :datetime="durationFormats.iso">
          {{ durationFormats.humanReadable }}
        </time>
      </div>
      <div class="grid grid-cols-[1fr_min-content_1fr] grid-areas-['left_center_right'] gap-x-4 items-center">
        <BaseToggler
          class="whitespace-nowrap min-w-6 justify-self-end"
          :aria-label="isShuffleModeEnabled ? t('disableShuffleTracks') : t('enableShuffleTracks')"
          v-model="isShuffleModeEnabled"
        >
          <BaseIcon class="text-2xl" :path="mdiShuffleVariant" />
        </BaseToggler>
        <ul class="flex justify-center gap-2">
          <li v-for="controlButton in controlButtons" :key="controlButton.key">
            <BaseButton
              :disabled="controlButton.disabled"
              class="whitespace-nowrap min-w-6 h-6 w-8"
              :aria-label="controlButton.ariaLabel"
              @click="controlButton.onClick"
            >
              <BaseIcon class="text-2xl" :path="controlButton.icon" />
            </BaseButton>
          </li>
        </ul>
        <ClientOnly v-if="!isMobile">
          <div class="flex h-full w-5/6 max-w-20 items-center">
            <PlayerSlider v-model="volume" @keydown.right="onKeyDownRightVolume" @keydown.left="onKeyDownLeftVolume" />
          </div>
        </ClientOnly>
      </div>
    </div>
  </BaseSwipable>
</template>

<script lang="ts" setup>
import { identity, syncRef, useClipboard, useLocalStorage, useMediaControls, useToggle } from '@vueuse/core';
import {
  mdiClose,
  mdiShuffleVariant,
  mdiLinkVariant,
  mdiPause,
  mdiPlay,
  mdiSkipBackward,
  mdiSkipForward,
} from '@mdi/js';
import { computed, useTemplateRef, h, shallowReactive } from 'vue';
import { useI18n } from 'vue-i18n';

import PlayerSlider from './components/PlayerSlider.vue';

import BaseButton from '@/components/ui/BaseButton.vue';
import BaseIcon from '@/components/ui/BaseIcon.vue';
import BaseSwipable from '@/components/ui/BaseSwipable.vue';
import BaseToggler from '@/components/ui/BaseToggler.vue';
import { millisecondsToHumanReadable } from '@/utils/millisecondsToHumanReadable';
import { to0To1Borders } from '@/utils/to0To1Borders';
import BaseAlwaysScrollable from '@/components/ui/BaseAlwaysScrollable.vue';
import { Temporal } from 'temporal-polyfill';
import { RouterLink, useRouter } from 'vue-router';
import { isNil } from '@etonee123x/shared/utils/isNil';
import { BUTTON } from '@/helpers/ui';
import { nonNullable } from '@/utils/nonNullable';
import { useIsMobile } from '@/composables/useIsMobile';
import ClientOnly from '../ClientOnly.vue';
import { NOTIFICATION_TYPES, useNotifications } from '@/plugins/notifications';
import { getRandomExceptCurrentIndex } from '@/utils/getRandomExceptCurrentIndex';
import { usePlayer } from '@/plugins/player';
import { useExplorerContext } from '@/views/Explorer/contexts/explorer';
import { useL10n } from '@/composables/useL10n';

const l10n = useL10n();

const { t } = useI18n({
  useScope: 'local',
  messages: {
    ru: {
      copied: 'Скопировано!',
      copyLink: 'Скопировать ссылку',
      previousTrack: 'Предыдущий трек',
      pauseTrack: 'Пауза трека',
      playTrack: 'Воспроизвести трек',
      nextTrack: 'Следующий трек',
      closePlayer: 'Закрыть плеер',
      enableShuffleTracks: 'Включить перемешивание треков',
      disableShuffleTracks: 'Выключить перемешивание треков',
    },
    en: {
      copied: 'Copied!',
      copyLink: 'Copy link',
      previousTrack: 'Previous track',
      pauseTrack: 'Pause track',
      playTrack: 'Play track',
      nextTrack: 'Next track',
      closePlayer: 'Close player',
      enableShuffleTracks: 'Enable shuffle tracks',
      disableShuffleTracks: 'Disable shuffle tracks',
    },
  },
});

const historyItems = shallowReactive<Array<number>>([]);
const [isShuffleModeEnabled] = useToggle();
const currentPlayingNumber = computed({
  get: () => {
    return player.playlist.value.findIndex((playlistItem) => {
      return playlistItem.src === player.theTrack.value?.src;
    });
  },
  set: (value) => {
    player.theTrack.value = player.playlist.value[value] ?? null;
  },
});

const isMobile = useIsMobile();

const router = useRouter();

const explorerContext = useExplorerContext();
const player = usePlayer();
const notifications = useNotifications();

const audio = useTemplateRef('audio');

const volumeLocalStorage = useLocalStorage('player-volume', 1);
const { playing: isPlaying, waiting: isWaiting, currentTime: currentTimeSeconds, volume } = useMediaControls(audio);

if (isMobile) {
  volume.value = 1;
} else {
  syncRef(volumeLocalStorage, volume, { transform: { ltr: identity, rtl: identity } });
}

const duration = computed(() => {
  return player.theTrack.value?.metadata.duration ?? 0;
});

const toggleIsPlaying = useToggle(isPlaying);

const shouldRenderButtonClose = computed(() => {
  return !(isPlaying.value || isWaiting.value);
});

const load = {
  next: () => {
    historyItems.push(currentPlayingNumber.value);

    currentPlayingNumber.value = isShuffleModeEnabled.value
      ? getRandomExceptCurrentIndex(player.playlist.value.length, currentPlayingNumber.value)
      : (currentPlayingNumber.value + 1) % player.playlist.value.length;
  },
  previous: () => {
    currentPlayingNumber.value =
      historyItems.length > 0
        ? (historyItems.pop() ?? 0)
        : (currentPlayingNumber.value - 1 + player.playlist.value.length) % player.playlist.value.length;
  },
};

const controlButtons = computed(() => {
  return [
    {
      key: 'previous',
      icon: mdiSkipBackward,
      onClick: load.previous,
      disabled: isShuffleModeEnabled.value && historyItems.length === 0,
      ariaLabel: t('previousTrack'),
    },
    isPlaying.value
      ? {
          key: 'pause',
          icon: mdiPause,
          onClick: () => {
            return toggleIsPlaying(false);
          },
          ariaLabel: t('pauseTrack'),
        }
      : {
          key: 'play',
          icon: mdiPlay,
          onClick: () => {
            return toggleIsPlaying(true);
          },
          ariaLabel: t('playTrack'),
        },
    {
      key: 'next',
      icon: mdiSkipForward,
      onClick: load.next,
      ariaLabel: t('nextTrack'),
    },
  ];
});

const onEnded = load.next;

const ComponentClose = computed(() => {
  const to = toOnClose();

  return to ? h(RouterLink, { to, class: BUTTON.default }) : BaseButton;
});

const toOnClose = () => {
  if (!player.theTrack.value) {
    return;
  }

  const currentFolderData = explorerContext.getFolderDataQuery.data.value;

  const maybeFile = currentFolderData?.file;

  if (!maybeFile) {
    return;
  }

  const lastNavigationItem = explorerContext.navigationLinks.value.at(-1);

  if (!lastNavigationItem) {
    return;
  }

  if (
    !player.playlist.value.some((track) => {
      return track.src === maybeFile.src;
    })
  ) {
    return;
  }

  return lastNavigationItem.to;
};

const unloadTrack = () => {
  player.theTrack.value = null;

  // Такой вот костыль... Нужен чтобы выгрузить текущий трек из управления аудио.
  // Без этого при закрытии плеера и нажатии на кнопку play/pause будет играть/останавливаться трек.
  audio.value?.load();
};

const onClickClose = unloadTrack;

const onSwiped = () => {
  const to = toOnClose();

  if (isNil(to)) {
    return;
  }

  router.push(to).then(unloadTrack);
};

const clipboard = useClipboard({
  source: () => {
    return encodeURI(
      new URL(
        l10n.localizePath(['explorer', nonNullable(player.theTrack.value).path].join('/')),
        globalThis.location.origin,
      ).toString(),
    );
  },
  legacy: true,
});

const onClickTitle = async () => {
  await clipboard.copy();
  notifications.notify(t('copied'), { type: NOTIFICATION_TYPES.SUCCESS });
};

const onKeyDownRightTime = () => {
  currentTimeSeconds.value += 5;
};

const onKeyDownLeftTime = () => {
  currentTimeSeconds.value -= 5;
};

const onKeyDownRightVolume = () => {
  volume.value = to0To1Borders(volume.value + 0.05);
};

const onKeyDownLeftVolume = () => {
  volume.value = to0To1Borders(volume.value - 0.05);
};

const millisecondsToTimeFormats = (milliseconds: number) => {
  return {
    humanReadable: millisecondsToHumanReadable(milliseconds),
    iso: Temporal.Duration.from({ milliseconds: Math.ceil(milliseconds) }).toString(),
  };
};

const currentTimeFormats = computed(() => {
  return millisecondsToTimeFormats(currentTimeSeconds.value * 1000);
});
const durationFormats = computed(() => {
  return millisecondsToTimeFormats(duration.value);
});
</script>

// apps/frontend/app/[locale]/_components/the-player/index.tsx
'use client';

import { useContext, useState } from 'react';
import { PlayerContext } from './player-context';
import { throwError } from '@/lib/utils/throw-error';
import { Button } from '@/components/ui/button';
import { Link, Pause, Play, Shuffle, SkipBack, SkipForward } from 'lucide-react';
import { millisecondsToHumanReadable } from '@/lib/utils/milliseconds-to-human-readable';
import { Slider } from '@/components/ui/slider';
import { Temporal } from 'temporal-polyfill';
import { isClient } from '@/lib/utils/target';
import { Toggle } from '@/components/ui/toggle';
import { useTranslations } from 'next-intl';
import { getRandomExceptCurrentIndex } from '@/lib/utils/get-random-except-current-index';

const millisecondsToTimeFormats = (milliseconds: number) => {
  return {
    humanReadable: millisecondsToHumanReadable(milliseconds),
    iso: Temporal.Duration.from({ milliseconds: Math.ceil(milliseconds) }).toString(),
  };
};

export const ThePlayer = () => {
  const playerContext = useContext(PlayerContext) ?? throwError();
  const [isShuffleModeEnabled, setIsShuffleModeEnabled] = useState(false);
  const [historyItems, setHistoryItems] = useState<Array<number>>([]);
  const t = useTranslations('ThePlayer');

  if (!playerContext.track) {
    return null;
  }

  const currentPlayingNumber = playerContext.playlist.findIndex((playlistItem) => {
    return playlistItem.src === playerContext.track?.src;
  });

  const setCurrentPlayingNumber = (currentPlayingNumber: number) => {
    playerContext.setTrack(playerContext.playlist[currentPlayingNumber]);
  };

  let audio: null | HTMLAudioElement = null;
  if (isClient) {
    audio = new Audio(playerContext.track.src);
  }

  const currentTimeSeconds = audio?.currentTime ?? 0;
  const duration = playerContext.track.metadata.duration ?? 0;
  const isPaused = audio?.paused ?? true;

  const load = {
    next: () => {
      historyItems.push(currentPlayingNumber);

      setCurrentPlayingNumber(
        isShuffleModeEnabled
          ? getRandomExceptCurrentIndex(playerContext.playlist.length, currentPlayingNumber)
          : (currentPlayingNumber + 1) % playerContext.playlist.length,
      );
    },
    previous: () => {
      setCurrentPlayingNumber(
        historyItems.length > 0
          ? (historyItems.pop() ?? 0)
          : (currentPlayingNumber - 1 + playerContext.playlist.length) % playerContext.playlist.length,
      );
    },
  };

  const onClickTitle = () => {
    //
  };

  const onEnded = () => {
    //
  };

  const controlButtons = [
    {
      key: 'previous',
      Icon: SkipBack,
      onClick: () => {
        load.previous();
      },
      disabled: isShuffleModeEnabled && historyItems.length === 0,
      ariaLabel: t('previousTrack'),
    },
    isPaused
      ? {
          key: 'play',
          Icon: Play,
          onClick: () => {
            audio?.play();
          },
          ariaLabel: t('playTrack'),
        }
      : {
          key: 'pause',
          Icon: Pause,
          onClick: () => {
            audio?.pause();
          },
          ariaLabel: t('pauseTrack'),
        },
    {
      key: 'next',
      Icon: SkipForward,
      onClick: () => {
        load.next();
      },
      ariaLabel: t('nextTrack'),
    },
  ];

  const currentTimeFormats = millisecondsToTimeFormats(currentTimeSeconds);
  const durationFormats = millisecondsToTimeFormats(duration);

  return (
    <section className="bg-background z-player border-t border-primary-500 pt-2 pb-4 w-full">
      <div className="layout-container flex flex-col gap-2 justify-center">
        <header className="flex items-center gap-2 text-lg">
          <h2>{playerContext.track.name}</h2>
          <Button aria-label={t('copyLink')} className="p-1" onClick={onClickTitle}>
            <Link />
          </Button>
        </header>
        <audio src={playerContext.track.src} autoPlay onEnded={onEnded} ref={null} />
        <div className="h-5 w-full mx-auto flex justify-between items-center gap-2">
          <time dateTime={currentTimeFormats.iso}>{currentTimeFormats.humanReadable}</time>
          {/* <PlayerSlider
            multiplier={duration / 1000}
            isLazy
            value={currentTimeSeconds}
            onKeyDownRight={onKeyDownRightTime}
            onKeyDownLeft={onKeyDownLeftTime}
          /> */}
          <Slider />
          <time dateTime={durationFormats.iso}>{durationFormats.humanReadable}</time>
        </div>
        <div className="grid grid-cols-[1fr_min-content_1fr] grid-areas-['left_center_right'] gap-x-4 items-center">
          <Toggle
            className="whitespace-nowrap min-w-6 justify-self-end"
            aria-label={isShuffleModeEnabled ? t('disableShuffleTracks') : t('enableShuffleTracks')}
            pressed={isShuffleModeEnabled}
            onPressedChange={setIsShuffleModeEnabled}
          >
            <Shuffle className="text-2xl" />
          </Toggle>
          <ul className="flex justify-center gap-2">
            {controlButtons.map((controlButton) => {
              return (
                <li key={controlButton.key}>
                  <Button
                    disabled={controlButton.disabled}
                    className="whitespace-nowrap h-full w-8"
                    aria-label={controlButton.ariaLabel}
                    onClick={controlButton.onClick}
                  >
                    <controlButton.Icon className="text-2xl" />
                  </Button>
                </li>
              );
            })}
          </ul>
          {/* <ClientOnly v-if="!isMobile">
          <div class="flex h-full w-5/6 max-w-20 items-center">
            <PlayerSlider v-model="volume" @keydown.right="onKeyDownRightVolume" @keydown.left="onKeyDownLeftVolume" />
          </div>
        </ClientOnly> */}
        </div>
      </div>
    </section>
  );
};
