// apps/frontend/src/components/ui/BaseHtml.vue
<template>
  <!-- eslint-disable-next-line vue/no-v-html -->
  <div class="custom-html" @click="onClick" v-html="html" />
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';

defineProps<{
  html: string;
}>();

const router = useRouter();

const onClick = (event: Event) => {
  const target = event.target;

  if (!(target instanceof HTMLAnchorElement)) {
    return;
  }

  if (!target.href || target.target === '_blank') {
    return;
  }

  event.stopPropagation();
  event.preventDefault();

  router.push(target.href.replace(globalThis.origin, ''));
};
</script>

// apps/frontend/src/shared/ui/base-html.tsx
'use client';

import { useRouter } from '@/i18n/navigation';

export const BaseHtml = ({ html }: { html: string }) => {
  const router = useRouter();

  const onClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (!(event.target instanceof HTMLAnchorElement)) {
      return;
    }

    if (!event.target.href || event.target.target === '_blank') {
      return;
    }

    event.stopPropagation();
    event.preventDefault();

    router.push(event.target.href.replace(globalThis.origin, ''));
  };

  return <div className="custom-html" onClick={onClick} dangerouslySetInnerHTML={{ __html: html }} />;
};
