// apps/frontend/src/components/ui/BaseAlwaysScrollable.vue
<template>
  <div class="overflow-hidden relative inline-flex" ref="container">
    <div
      :style="{
        '--scroll-x-diff': diffFormatted,
        '--scroll-x-duration': duration,
      }"
      class="whitespace-nowrap m-(--base-always-scrollable--content--margin)"
      :class="isAnimated && 'animate-scroll-x [animation-duration:var(--scroll-x-duration)]'"
      ref="content"
    >
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useElementSize } from '@vueuse/core';
import { computed, useTemplateRef } from 'vue';

withDefaults(
  defineProps<
    Partial<{
      duration: string;
    }>
  >(),
  {
    duration: '5000ms',
  },
);

const container = useTemplateRef('container');
const content = useTemplateRef('content');

const { width: widthContainer } = useElementSize(container, undefined, { box: 'border-box' });
const { width: widthContent } = useElementSize(content, undefined, { box: 'border-box' });

const diff = computed(() => {
  return widthContent.value - widthContainer.value;
});

const diffFormatted = computed(() => {
  return `-${diff.value}px`;
});

const isAnimated = computed(() => {
  return diff.value > 0;
});
</script>

// apps/frontend/src/shared/ui/base-always-scrollable.tsx
'use client';

import { type ComponentProps, type CSSProperties, type PropsWithChildren, useRef } from 'react';
import { cn } from '@/shared/utils/cn';
import { useElementSize } from '@reactuses/core';

export const BaseAlwaysScrollable = ({
  children,
  className,
  duration = '10000ms',
}: PropsWithChildren<
  {
    duration?: string;
  } & Pick<ComponentProps<'div'>, 'className'>
>) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  const [widthContainer] = useElementSize(containerRef, { box: 'border-box' });
  const [widthContent] = useElementSize(contentRef, { box: 'border-box' });

  const diff = widthContent - widthContainer;

  const style = {
    '--scroll-x-diff': `-${diff}px`,
    '--scroll-x-duration': duration,
  } as CSSProperties;

  return (
    <div className={cn('relative inline-flex overflow-hidden', className)} ref={containerRef}>
      <div
        className={cn(
          'm-(--base-always-scrollable--content--margin) whitespace-nowrap',
          diff > 0 && 'animate-scroll-x animation-duration-(--scroll-x-duration)',
        )}
        ref={contentRef}
        style={style}
      >
        {children}
      </div>
    </div>
  );
};
