// apps/frontend/src/views/Explorer/components/ExplorerElementFileAudio.vue
<template>
  <ElementFileWrapper :element :to>
    <ul class="flex gap-4 overflow-x-auto">
      <li
        v-for="metadataItem in metadataItems"
        :title="metadataItem.title"
        class="flex flex-col items-center"
        :key="metadataItem.key"
      >
        <BaseIcon class="text-2xl h-6" :path="metadataItem.path" />
        <span class="text-center max-w-40">
          {{ metadataItem.value }}
        </span>
      </li>
    </ul>
  </ElementFileWrapper>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import { computed } from 'vue';
import { mdiClockOutline, mdiAccountOutline, mdiAlbum, mdiCalendarBlankOutline, mdiMetronome } from '@mdi/js';

import ElementFileWrapper from './_ElementFileWrapper.vue';
import type { Props as PropsElementFileWrapper } from './_ElementFileWrapper.vue';

import { millisecondsToHumanReadable } from '@/utils/millisecondsToHumanReadable';
import BaseIcon from '@/components/ui/BaseIcon';
import type { components } from '@/types/openapi';

const props = defineProps<{
  element: components['schemas']['FolderDataItemAudio'];
  to: PropsElementFileWrapper['to'];
}>();

const { t } = useI18n({
  useScope: 'local',
  messages: {
    ru: {
      duration: 'Длительность',
      artists: 'Исполнитель(-и)',
      album: 'Альбом',
      year: 'Год выхода',
      bpm: 'Темп',
    },
    en: {
      duration: 'Duration',
      artists: 'Artist(-s)',
      album: 'Album',
      year: 'Release year',
      bpm: 'BPM',
    },
  },
});

const metadataItems = computed(() => {
  return [
    ...(props.element.metadata.duration
      ? [
          {
            key: 'duration',
            title: t('duration'),
            path: mdiClockOutline,
            value: millisecondsToHumanReadable(props.element.metadata.duration),
          },
        ]
      : []),
    ...(props.element.metadata.artists.length > 0
      ? [
          {
            key: 'artists',
            title: t('artists'),
            path: mdiAccountOutline,
            value: props.element.metadata.artists.join(' & '),
          },
        ]
      : []),
    ...(props.element.metadata.album
      ? [
          {
            key: 'album',
            title: t('album'),
            path: mdiAlbum,
            value: props.element.metadata.album,
          },
        ]
      : []),
    ...(props.element.metadata.year
      ? [
          {
            key: 'year',
            title: t('year'),
            path: mdiCalendarBlankOutline,
            value: String(props.element.metadata.year),
          },
        ]
      : []),
    ...(props.element.metadata.bpm
      ? [
          {
            key: 'bpm',
            title: t('bpm'),
            path: mdiMetronome,
            value: String(props.element.metadata.bpm),
          },
        ]
      : []),
  ];
});
</script>

// apps/frontend/src/app/[locale]/explorer/[[...segments]]/_components/explorer-element-file/explorer-element-file-audio.tsx
import { Item, ItemContent, ItemDescription, ItemGroup, ItemHeader, ItemMedia, ItemTitle } from '@/shared/ui/ds/item';
import { Separator } from '@/shared/ui/ds/separator';
import { Link } from '@/i18n/navigation';
import { type components } from '@/lib/types/openapi';
import { millisecondsToHumanReadable } from '@/shared/utils/milliseconds-to-human-readable';
import { Calendar, Clock, Disc3, Metronome, Users } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { type ComponentProps } from 'react';
import { ExplorerElementTime } from './explorer-element-time';

export const ExplorerElementFileAudio = ({
  element,
  ...props
}: ComponentProps<typeof Link> & { element: components['schemas']['FolderDataItemAudio'] }) => {
  const t = useTranslations('ExplorerElementAudio');

  const metadataItems = [
    ...(element.metadata.duration
      ? [
          {
            key: 'duration',
            title: t('duration'),
            Icon: Clock,
            value: millisecondsToHumanReadable(element.metadata.duration),
          },
        ]
      : []),
    ...(element.metadata.artists.length > 0
      ? [
          {
            key: 'artists',
            title: t('artists'),
            Icon: Users,
            value: element.metadata.artists.join(' & '),
          },
        ]
      : []),
    ...(element.metadata.album
      ? [
          {
            key: 'album',
            title: t('album'),
            Icon: Disc3,
            value: element.metadata.album,
          },
        ]
      : []),
    ...(element.metadata.year
      ? [
          {
            key: 'year',
            title: t('year'),
            Icon: Calendar,
            value: element.metadata.year,
          },
        ]
      : []),
    ...(element.metadata.bpm
      ? [
          {
            key: 'bpm',
            title: t('bpm'),
            Icon: Metronome,
            value: element.metadata.bpm,
          },
        ]
      : []),
  ];

  return (
    <article className="contents">
      <Item className="border-primary" render={<Link {...props} />}>
        <ItemHeader>
          <header className="text-lg">{element.name}</header>
          <ExplorerElementTime element={element} />
        </ItemHeader>
        <Separator />
        <ItemContent className="w-full">
          <ItemGroup className="flex-row overflow-x-auto">
            {metadataItems.map((metadataItem) => {
              return (
                <Item size="xs" className="flex-nowrap" key={metadataItem.key}>
                  <ItemMedia className="self-center! pb-0.5">
                    <metadataItem.Icon className="size-6" />
                  </ItemMedia>
                  <ItemContent className="text-nowrap">
                    <ItemTitle className="text-muted-foreground font-normal">{metadataItem.title}</ItemTitle>
                    <ItemDescription className="text-secondary-foreground text-sm!">
                      {metadataItem.value}
                    </ItemDescription>
                  </ItemContent>
                </Item>
              );
            })}
          </ItemGroup>
        </ItemContent>
      </Item>
    </article>
  );
};
